# include <stdlib.h>
# include <stdio.h>
# include <string.h>    
# include <sys/socket.h>
# include <arpa/inet.h>
# include <unistd.h> 
# include "myTPA.h"
# include "myAESstorage.h" 

int main(void)
{
	int server_socket, storage_socket, client_socket , c , read_size , loop = 0;
	struct sockaddr_in TPAserver, Storageserver,client;
	char client_message[65],token[32],storage_message[67];
	char *user_name,*password;

	//Create socket for client
	server_socket = socket(AF_INET , SOCK_STREAM , 0);
	if (server_socket == -1){
		printf("Could not create socket");
	}
	     
	//Prepare the sockaddr_in structure
	TPAserver.sin_family = AF_INET;
	TPAserver.sin_addr.s_addr = INADDR_ANY;
	TPAserver.sin_port = htons( 1231 );
	     
	//Bind
	if( bind(server_socket,(struct sockaddr *)&TPAserver , sizeof(TPAserver)) < 0){
		//print the error message
		perror("Error, failed to bind");
		return 1;
	}
	puts("Server create successfully");

	//Listen to max of 5 clients
	listen(server_socket , 5);
	     
	myTPA_load_account();
	puts("Load account list successfully");

	//Accept and incoming connection
	puts("Waiting for incoming connections...");
	c = sizeof(struct sockaddr_in);
	     
	//accept connection from an incoming client
	client_socket = accept(server_socket, (struct sockaddr *)&client, (socklen_t*)&c);
	if (client_socket < 0){
		perror("Error, failed to accept");
		return 1;
	}
	puts("Connection between TPAserver and client accepted");
	    
    	//Receive a message from client
	while(!loop){//check if the user is authenticated or not
 		memset(client_message,0,sizeof(client_message));//clear buffer
		if((read_size = recv(client_socket , client_message , sizeof(client_message) , 0)) > 0 ){
			
			//split string into smaller parts
			char *copy = malloc(sizeof(client_message));
			strcpy(copy,client_message);
			user_name = strsep(&copy,",");
			printf("User name:%s\n",user_name);
			password = strsep(&copy,",");
			printf("Password:%s\n",password);
			free(copy);

			memset(client_message,0,sizeof(client_message));
			if(myTPA_authentication(user_name,password,token)){
				printf("Token generated by TPA:%s\n",token);
				loop = 1;//user is authenticated

				//create socket for new connection
				storage_socket = socket(AF_INET , SOCK_STREAM , 0);
				if (storage_socket == -1){
					printf("Could not create socket");
				}

				//setup info about Storageserver
				Storageserver.sin_addr.s_addr = inet_addr("127.0.0.1");
				Storageserver.sin_family = AF_INET;
				Storageserver.sin_port = htons( 1233 );

				//Connect to Storageserver
				if (connect(storage_socket , (struct sockaddr *)&Storageserver , sizeof(Storageserver)) < 0)
					perror("Error, Established connection with Storageserver");
				else 
					puts("Established connection with Storageserver");

				//send message to Storageserver to register the user
				memset(storage_message,0,sizeof(storage_message));
				strcat(storage_message,"0");
				strcat(storage_message,",");
				strcat(storage_message,user_name);
				strcat(storage_message,",");
				strcat(storage_message,token);
				write(storage_socket , storage_message, sizeof(storage_message));
		
				//wait for respond from Storageserver
				memset(storage_message,0,sizeof(storage_message));
				while((read_size = recv(storage_socket , storage_message , sizeof(storage_message) , 0)) < 0);
				if(!strcmp(storage_message,"1"))//register successed
					printf("User %s registered successfully with token %s\n",user_name,token);
				else//register failed
					puts("Error, failed to register");
			}
			write(client_socket , token, sizeof(token));//send respond to client, if token is empty means user is not authenticated
			for(int i=0;i<50;i++)printf("-");
			puts("");
		}else
			puts("Error, failed to receive message from client.");
	}
	//close socket
   	close(storage_socket);
	close(client_socket);
	close(server_socket);
	puts("TPAserver closed");
        return 0;
}
